const actors = [
    {
        "adult": false,
        "also_known_as": [
            "Elena Purnell",
            "엘라 퍼넬",
            "Έλα Παρνέλ",
            "Елла Пернелл",
            "เอลลา เพอร์เนล",
            "艾拉·珀内尔",
            "艾拉・彭内爾",
            "เอลล่า เพอร์เนลล์",
            "艾拉彭內爾"
        ],
        "biography": "Ella Purnell (born 17 September 1996) is an English actress. She began her career as a child actress on the West End and in the film Never Let Me Go (2010).  Purnell used to attend weekly classes at Sylvia Young Theatre School, studying acting, singing and dance.  Description above from Purnell's page on Wikipedia, The Free Encyclopedia",
        "birthday": "1996-09-17",
        "deathday": null,
        "gender": 1,
        "homepage": "https://www.curtisbrown.co.uk/client/ella-purnell",
        "id": 989325,
        "imdb_id": "nm3480246",
        "known_for_department": "Acting",
        "name": "Ella Purnell",
        "place_of_birth": "London, England, UK",
        "popularity": 168.983,
        "profile_path": "/5PscK9HNXGFQMIxkpbR8ObB7vuR.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "קיאנו ריבס",
            "キアヌ・チャールズ・リーブス",
            "キアヌ・リーブス",
            "基努·里维斯",
            "Кіану Рівз",
            "Keanu Charles Reeves",
            "Dogstar",
            "키아누 리브스",
            "基努·李維"
        ],
        "biography": "Keanu Charles Reeves is a Canadian actor. Reeves is known for his roles in Bill & Ted's Excellent Adventure, Speed, Point Break, and The Matrix franchise as Neo.\n\nHe has collaborated with major directors such as Stephen Frears (in the 1988 period drama Dangerous Liaisons); Gus Van Sant (in the 1991 independent film My Own Private Idaho); and Bernardo Bertolucci (in the 1993 film Little Buddha). Referring to his 1991 film releases, The New York Times' critic, Janet Maslin, praised Reeves' versatility, saying that he \"displays considerable discipline and range. He moves easily between the buttoned-down demeanor that suits a police procedural story and the loose-jointed manner of his comic roles.\" A repeated theme in roles he has portrayed is that of saving the world, including the characters of Ted Logan, Buddha, Neo, Johnny Mnemonic, John Constantine and Klaatu.",
        "birthday": "1964-09-02",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 6384,
        "imdb_id": "nm0000206",
        "known_for_department": "Acting",
        "name": "Keanu Reeves",
        "place_of_birth": "Beirut, Lebanon",
        "popularity": 123.242,
        "profile_path": "/4D0PpNI0kmP58hgrwGC3wCjxhnm.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Theodore Peter James Kinnaird Taptiklis",
            "테오 제임스",
            "席歐·詹姆斯"
        ],
        "biography": "Theodore Peter James Kinnaird Taptiklis (born 16 December 1984) is an English actor. He is known for portraying Tobias \"Four\" Eaton in The Divergent Series film trilogy. James starred in the horror films Underworld: Awakening (2012) and Underworld: Blood Wars (2016), the action film How It Ends (2018), and the science fiction film Archive (2020). In television, he appeared in the crime drama series Golden Boy (2012) and the romance series The Time Traveler's Wife (2022).\n\nDescription above from the Wikipedia article Theo James, licensed under CC-BY-SA, full list of contributors on Wikipedia.",
        "birthday": "1984-12-16",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 587020,
        "imdb_id": "nm3772243",
        "known_for_department": "Acting",
        "name": "Theo James",
        "place_of_birth": "High Wycombe, England, UK",
        "popularity": 87.53,
        "profile_path": "/lSC4cMhcQeCjPFkK6qCjSGDSeR3.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Kaya Scodelario-Davis",
            "Kaya Humphrey",
            "카야 스코델라리오",
            "Кая Скоделарио",
            "Κάγια Σκοντελάριο",
            "Κάγια Χάμφρεϊ",
            "Κάγια Σκοντελάριο-Ντέιβις",
            "Κάγια Ρόουζ Σκοντελάριο-Ντέιβις (το γένος Humphrey)",
            "Kaya Rose Humphrey",
            "Kaya Rose Scodelario-Davis",
            "卡雅·斯考达里奥",
            "カヤ・スコデラリオ"
        ],
        "biography": "Kaya Rose Scodelario-Davis (née Humphrey; born 13 March 1992) is an English actress best known for her roles as Effy Stonem on the E4 teen drama Skins (2007–2010, 2013), and Teresa in the Maze Runner film series (2014–2018). Other roles include Catherine Earnshaw in Andrea Arnold's Wuthering Heights (2011), Carina Smyth in Pirates of the Caribbean: Dead Men Tell No Tales (2017), Carole Ann Boone in Extremely Wicked, Shockingly Evil and Vile (2019), Haley Keller in Crawl (2019), Katarina Baker in the Netflix original series Spinning Out (2020) and Claire Redfield in Resident Evil: Welcome to Raccoon City (2021).",
        "birthday": "1992-03-13",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 115150,
        "imdb_id": "nm2546012",
        "known_for_department": "Acting",
        "name": "Kaya Scodelario",
        "place_of_birth": "Haywards Heath, West Sussex, London, England, UK",
        "popularity": 88.527,
        "profile_path": "/VwNLOYmKs1UD7jf3EptVglUSvw.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Jennie",
            "제니",
            "김제니",
            "제니김",
            "Jennie Ruby Jane",
            "金智妮"
        ],
        "biography": "Jennie Kim (born January 16, 1996), known mononymously as Jennie, is a South Korean singer, rapper, and actress. Born and raised in South Korea, Jennie studied in New Zealand for five years before returning to South Korea in 2010. She debuted as a member of the girl group Blackpink, formed by YG Entertainment, in August 2016. In November 2018, Jennie made her debut as a solo artist with the single \"Solo\", which topped both the Gaon Digital Chart and Billboard's World Digital Songs chart. In 2023, she made her acting debut under the stage name Jennie Ruby Jane in the HBO series The Idol.",
        "birthday": "1996-01-16",
        "deathday": null,
        "gender": 1,
        "homepage": "https://www.ygfamily.com/artist/Main.asp?LANGDIV=K&ATYPE=2&ARTIDX=77",
        "id": 1875841,
        "imdb_id": "nm8707185",
        "known_for_department": "Acting",
        "name": "Jennie Kim",
        "place_of_birth": "Seoul, South Korea",
        "popularity": 88.057,
        "profile_path": "/17A6a2ZJQWXbMTPfhpTNBQhtDv7.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Райан Рейнольдс",
            "رايان رينولدز",
            "라이언 레이놀즈",
            "ライアン・レイノルズ",
            "ไรอัน เรย์โนลส์",
            "萊恩·雷諾斯",
            "Раян Рейнольдс",
            "Ryan Rodney Reynolds",
            "Ράιαν Ρέινολντς",
            "瑞安·雷诺兹",
            "Champ Nightengale",
            "রায়ান রেনল্ডস্",
            "ראיין רנולדס"
        ],
        "biography": "Ryan Rodney Reynolds (born October 23, 1976) is a Canadian actor and film producer. He began his career starring in the Canadian teen soap opera Hillside (1991–1993), and had minor roles before landing the lead role on the sitcom Two Guys and a Girl between 1998 and 2001. Reynolds then starred in a range of films, including comedies such as National Lampoon's Van Wilder (2002), Waiting... (2005), and The Proposal (2009). He also performed in dramatic roles in Buried (2010), Woman in Gold (2015), and Life (2017), starred in action films such as Blade: Trinity (2004), Green Lantern (2011), 6 Underground (2019) and Free Guy (2021), and provided voice acting in the animated features The Croods (2013), Turbo (2013), Pokémon: Detective Pikachu (2019) and The Croods: A New Age (2020).\n\nReynolds' biggest commercial success came with the superhero films Deadpool (2016) and Deadpool 2 (2018), in which he played the title character. The former set numerous records at the time of its release for an R-rated comedy and his performance earned him nominations at the Critics' Choice Movie Awards and the Golden Globe Awards.",
        "birthday": "1976-10-23",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 10859,
        "imdb_id": "nm0005351",
        "known_for_department": "Acting",
        "name": "Ryan Reynolds",
        "place_of_birth": "Vancouver, British Columbia, Canada",
        "popularity": 114.114,
        "profile_path": "/2Orm6l3z3zukF1q0AgIOUqvwLeB.jpg"
    },
    {
        "adult": false,
        "also_known_as": [],
        "biography": "",
        "birthday": null,
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 1947579,
        "imdb_id": "nm3743244",
        "known_for_department": "Acting",
        "name": "Laura Sépul",
        "place_of_birth": "Belgium",
        "popularity": 107.594,
        "profile_path": "/rlyHCwbkfQGrMqBuKBuKnBmEiFb.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Άνια Τέιλορ-Τζόι",
            "Аня Тейлор-Джой",
            "安雅·泰勒-乔伊",
            "安雅‧泰勒-喬伊",
            "안야 테일러조이",
            "アニャ・テイラー＝ジョイ",
            "アニャ・テイラー・ジョイ",
            "אניה טיילור-ג'וי",
            "Анја Џозефин Мари Тејлор-Џој",
            "安雅·泰勒-喬伊"
        ],
        "biography": "Anya-Josephine Marie Taylor-Joy (born 16 April 1996) is a British-American actress and model.\n\nShe left school at age sixteen and began to pursue an acting career. After small television roles, she made her film debut with the lead role of Thomasin in the horror film The Witch (2015). She went on to star in the horror film Split and the black comedy Thoroughbreds (both 2017). She also appeared in the drama miniseries The Miniaturist (2017), the fifth and sixth series of Peaky Blinders (2019–2022) and The Dark Crystal: Age of Resistance (2019), and the superhero film Glass (2019), reprising her role from Split. Taylor-Joy will voice Princess Peach in the upcoming Mario film (2022) and portray the title character in Furiosa (2024).",
        "birthday": "1996-04-16",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 1397778,
        "imdb_id": "nm5896355",
        "known_for_department": "Acting",
        "name": "Anya Taylor-Joy",
        "place_of_birth": "Miami, Florida, USA",
        "popularity": 105.928,
        "profile_path": "/yZpghhtKM2VZHDx6JGAZqAVU4PL.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Thomas Stanley Holland",
            "トム・ホランド",
            "톰 홀랜드",
            "توم هولاند",
            "ทอม ฮอลแลนด์",
            "汤姆·赫兰德",
            "Τομ Χόλαντ",
            "湯姆·霍蘭德",
            "טום הולנד",
            "תומאס סטנלי הולנד",
            "ტომ ჰოლანდი",
            "टॉम हॉलैंड",
            "ทอมัส สแตนลีย์ ฮอลแลนด์"
        ],
        "biography": "Thomas \"Tom\" Stanley Holland is an English actor and dancer.\n\nHe is best known for playing Peter Parker / Spider-Man in the Marvel Cinematic Universe and has appeared as the character in six films: Captain America: Civil War (2016), Spider-Man: Homecoming (2017), Avengers: Infinity War (2018), Avengers: Endgame (2019), Spider-Man: Far From Home (2019), and Spider-Man: No Way Home (2021).\n\nHe is also known for playing the title role in Billy Elliot the Musical at the Victoria Palace Theatre, London, as well as for starring in the 2012 film The Impossible.",
        "birthday": "1996-06-01",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 1136406,
        "imdb_id": "nm4043618",
        "known_for_department": "Acting",
        "name": "Tom Holland",
        "place_of_birth": "Surrey, England, UK",
        "popularity": 103.096,
        "profile_path": "/yxYOaalFh8SUwNE5C0wzOwF89Ny.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Thomas Jeffrey Hanks",
            "Том Хэнкс",
            "توم هانكس",
            "トム・ハンクス",
            "톰 행크스",
            "ทอม แฮงส์",
            "汤姆·汉克斯",
            "Том Генкс",
            "Том Хенкс",
            "Томас Джеффрі Генкс",
            "Τομ Χανκς",
            "टॉम हैंक्स",
            "ടോം ഹാങ്ക്സ്",
            "湯姆‧漢克斯",
            "湯姆·漢克",
            "托马斯·杰弗里·汉克斯",
            "Thomas Hanks",
            "湯漢斯 飾",
            "טום הנקס",
            "湯姆·漢克斯"
        ],
        "biography": "Thomas Jeffrey Hanks (born July 9, 1956) is an American actor and filmmaker. Known for both his comedic and dramatic roles, Hanks is one of the most popular and recognizable film stars worldwide, and is widely regarded as an American cultural icon.\n\nHanks made his breakthrough with leading roles in the comedies Splash (1984) and Big (1988). He won two consecutive Academy Awards for Best Actor for starring as a gay lawyer suffering from AIDS in Philadelphia (1993) and a young man with below-average IQ in Forrest Gump (1994). Hanks collaborated with film director Steven Spielberg on five films: Saving Private Ryan (1998), Catch Me If You Can (2002), The Terminal (2004), Bridge of Spies (2015), and The Post (2017), as well as the 2001 miniseries Band of Brothers, which launched him as a director, producer, and screenwriter.\n\nHanks' other notable films include the romantic comedies Sleepless in Seattle (1993) and You've Got Mail (1998); the dramas Apollo 13 (1995), The Green Mile (1999), Cast Away (2000), Road to Perdition (2002), and Cloud Atlas (2012); and the biographical dramas Saving Mr. Banks (2013), Captain Phillips (2013), Sully (2016), and A Beautiful Day in the Neighborhood (2019). He has also appeared as the title character in the Robert Langdon film series, and has voiced Sheriff Woody in the Toy Story film series.\n\nDescription above from the Wikipedia article Tom Hanks, licensed under CC-BY-SA, full list of contributors on Wikipedia.",
        "birthday": "1956-07-09",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 31,
        "imdb_id": "nm0000158",
        "known_for_department": "Acting",
        "name": "Tom Hanks",
        "place_of_birth": "Concord, California, USA",
        "popularity": 110.946,
        "profile_path": "/xndWFsBlClOJFRdhSt4NBwiPq2o.jpg"
    }
];

export default actors;